services:
  first_app:
    image: links/first_app
    build:
      context: ./first_app
    volumes:
      - ./first_app:/code
    command: "fastapi run first_main.py --port 8001 --host localhost"
    links:
      - second_app:calculator
    ports:
      - 8000:8001

  second_app:
    image: links/second_app
    build:
      context: ./second_app
    volumes:
      - ./second_app:/code
    command: "fastapi run second_main.py --port 80"