apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
spec:
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
      - name: calculator
        image: arsenoks4132d/fastapi_calculator_api:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
